### ISSUE TITLE
change structure of departments and schools

### ISSUE THREAD

**Issue by sbillinge** [Billingegroup/rg-db-public#23]
These can be dicts as now, but if we want to have aka's for them we will have to make the dict values as tuples or lists or sthg.  e.g., ``{seas: ("Fu Foundation School of School of Engineering and Applied Science",["Columbia Engineering","School of Engineering and Applied Science","SEAS"])``. Its messy!
The basic idea is that the tuple is ``(name,aka)`` but the ``aka`` is a list

I guess it could be a dict of dicts actually, so ``{seas: {name: "Fu", aka: ["SEAS",]}``.  I think that would be more standard.

**Comment by CJ-Wright** [comment]
:+1: for dict of dicts

**Comment by sbillinge** [comment]
fixed in 3603da58bdbe
