### ISSUE TITLE
fix ci

### ISSUE THREAD

**Issue by CJ-Wright** [Billingegroup/rg-db-public#94]
It seems that the CI:
1. Isn't checking the validation
    1. Needs to run using the local
1. Is trying to build the website and failing

**Comment by sbillinge** [comment]
We need the UTF8 PR merged on regolith and then a conda release for the
validation to pass

**Comment by sbillinge** [comment]
Sorry, I forgot we were missing a merge when I asked you to release....😔

**Comment by CJ-Wright** [comment]
I did both of those, yesterday.

**Comment by CJ-Wright** [comment]
The validation does pass, we have a built website and everything.

**Comment by sbillinge** [comment]
I think the utf8 merge is not in tho, right? I checked today.

**Comment by CJ-Wright** [comment]
I guess that didn't go in, although the website does build and validate.
